//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klienci
    {
        public int IDKlienta { get; set; }
        public string Nazwisko { get; set; }
        public string Imie { get; set; }
        public Nullable<int> Wiek { get; set; }
        public string Adres { get; set; }
        public string Telefon { get; set; }
        public string Plec { get; set; }

        public static explicit operator List<object>(Klienci v)
        {
            throw new NotImplementedException();
        }
    }
}
